--- 
- 
  gather_facts: true
  hosts: ip-172-31-43-14.ec2.internal
  tasks: 
    - 
      debug: 
        msg: "{{ shell_result.stdout }}"
      name: "Install maven in redhat"
      register: shell_result
      shell: |
          sudo yum install java-1.8.0-openjdk-devel -y
          sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
          sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
          sudo yum install -y apache-maven -y
          sudo    mvn --version
      when: "shell_result.stderr == \"\""
