---
- hosts: all
  tasks:
  - name:
    command: whoami
  - name: ping all
    ping: 
  - name: findout current directory
    raw: pwd
  - name: install tree
    yum:
      name: tree
      state: present
    when: ansible_os_family == "redhat"
  - name: install tree
    apt:
      name: tree 
      state: present
    when: ansible_os_family == "ubuntu"

