---
- hosts: rhel
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ansible

  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

    notify: restart webservies

  - command: systemctl status httpd
    register: myapache
  - debug:
      msg: " {{ myapache.stdout  }} "
    when: myapache.stderr == ""
  - debug:
      msg: " {{ myapache.stdoerr  }} "
    when: myapache.stderr != ""

    handlers:
      name: restart apache
      service: 
        name: httpd
        state: restarted 
